app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from config import Config

bootstrap = Bootstrap()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    Config.init_app(app)

    bootstrap.init_app(app)

    from main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from o2sc import o2sc as o2sc_blueprint
    app.register_blueprint(o2sc_blueprint)

    return app

app = create_app()

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template

from . import main

@main.route('/')
def index():
    return render_template('index.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}John J. Caine{% endblock %}

{% block head %}
{{ super() }}
<link rel="stylesheet" href="static/css/darkly-bootstrap.min.css" />
<link href="/static/css/site.css" rel="stylesheet" />
{% endblock %}

{% block navbar %}
<div id="menu" class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button class="btn btn-success navbar-toggle"
                    data-toggle="collapse"
                    data-target=".navbar-collapse"><span class="glyphicon glyphicon-chevron-down"></span></button>
            <div id="logo">
                <a href=''><h4>John J. Caine</h4></a>
            </div>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li class="nav"><a href="{{ url_for('main.index', _external=True) }}">Home</a></li>
                <li class="nav"><a href="{{ url_for('o2sc.o2sc', _external=True) }}">O2SC</a></li>
                <li class="nav"><a href="#">About</a></li>
                <li class="nav"><a href="#">Contact</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<section id="body" class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}




</section>
<footer class="container pull-down">
    <div class="row">
        <p><span class="glyphicon glyphicon-copyright-mark"></span> 2014 -  John J. Caine</p>
    </div>
</footer>
{%  endblock %}

{% block scripts %}
{{ super() }}
    <script src="static/js/site.js"></script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block page_content %}
    <h3 class="page-header">John J. Caine.com</h3>
{% endblock %}

app/templates/o2sc/upload.html
{% extends "base.html" %}

{% block title %}O2SC{% endblock %}

{% block page_content %}

<h3 class="page-header">Ordered to Self Configured DIP Converter - v0.1</h3>
<div class="container">
    <form method="post" enctype=multipart/form-data>
        <div class="form-group col-md-5">
            <label class="control-label" for="file">Ordered DIP File</label><br>
            <input class="form-control" type="file" name="file" /><br>
            <label class="control-label" for="delimiter">Delimiter</label><br>
            Example: In the string "123","456" the comma is the Delimiter
            <input class="form-control" type="text" name="delimiter" /><br>
            <label class="control-label" for="quote-char">Quote Character (optional)</label><br>
            Example: In the string "123","456" the quotation mark is the Quote Character
            <input class="form-control" type="text" name="quote-char" /><br>
            <label class="control-label" for="doc-type">Doc Type</label><br>
            *This will be the doc type for all documents in the file. Leave blank if your DIP file has a doc type and
                map the field below.<br>
            <input class="form-control" type="text" name="doc-type" /><br>
            <label class="control-label" for="file-path-field">Name of header that contains the file path</label><br>
            <input class="form-control" type="text" name="file-path-field" /><br>
            <label class="control-label" for="unique-id">Name of header that contains the unique document identifier</label><br>
            <input class="form-control" type="text" name="unique-id" /><br>
            <label class="control-label" for="omit">Fields to Omit (comma separated)</label><br>
            <textarea class="form-control" type="textarea" rows="4" name="omit"></textarea><br>
            <label class="control-label" for="header-mapping">Header Mapping</label><br>
            Example: 'File Date': '>>DocDate', 'Doc Type': '>>DocType' (don't map the file path header)<br>
            <textarea class="form-control" type="textarea" rows="4" name="header-mapping"></textarea><br>
            <input type="submit" value="Upload">
        </div>
    </form>
</div>
{% endblock %}